version: '2.3'

services:
  mysql:
    container_name: taa-mysql_container
    image: mysql:8.0.32-oracle
    environment:
      MYSQL_ROOT_PASSWORD: my-password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  cloudbeaver:
    container_name: taa-cloudbeaver_container
    image: dbeaver/cloudbeaver:23.2.0
    depends_on:
      mysql:
        condition: service_started
    restart: always
    ports:
      - '8978:8978'
    volumes:
      - cb-data:/opt/cloudbeaver/workspace

  myapp:
    container_name: myapp_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7001:7001'
    depends_on:
      mysql:
        condition: service_started
    env_file:
      - ./.env

volumes:
  db-data:
  cb-data: